name: Test-Git-Actions

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  test-context:
    name: Test Git Context
    runs-on: ubuntu-latest
    steps:
      - name: dump github context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
