name: List Issues

on: [workflow_dispatch]
  # schedule:
  #  - cron: "*/2 * * * *"

jobs:
  list-issues:
    runs-on: ubuntu-latest

    steps:
      - name: List all issues
        id: list-all-issues
        run: |
          created=$(date -d "14 days ago" +%Y-%m-%dT%H:%M:%SZ)
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues?since=${created}" \
          | jq '.[] | select(.created_at > "'${created}'") | [.number, .title, .created_at] | @csv' \
          | column -t \
          | xargs -0 -I{} echo "issues={}" >>$GITHUB_OUTPUT
                 
                 
 
          #| jq -r '.[] | [.number, .title, .created_at] | @csv' \
          #| tee /dev/stderr \
          #| xargs -I{} echo "issues={}" >>$GITHUB_OUTPUT
          
          
#       - name: filter created issues
#         id: filter-created-issues
#         run: |
#           created=$(date -d "7 days ago" +%Y-%m-%dT%H:%M:%SZ)
#           for item in ${{ steps.list-all-issues.outputs.issues }}; do
#             echo "The issue is $item"
#             done
          

      - name: Use the issues
        run: echo "The issues are ${{ steps.list-all-issues.outputs.issues }}"
               
               
