name: List Issues

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  list-issues:
    runs-on: ubuntu-latest

    steps:
      - name: List issues
        id: list-issues
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/issues" \
          | jq '.[].number' \
          | tr '\n' ',' \
          | sed 's/,$//' \
          | tee /dev/stderr \
          | xargs -I{} echo "::set-output name=issues::{}"

      - name: Use the issues
        run: echo "The issues are ${{ steps.list-issues.outputs.issues }}"
               
               
